version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
      #- --lower_case_table_names=0
    restart: always
    environment:
      MYSQL_DATABASE: "mkstudio"
      MYSQL_USER: "migue"
      MYSQL_PASSWORD: "mkstudio"
      MYSQL_ROOT_PASSWORD: "mkstudio"

    ports:
      - 3311:3306
    expose:
      - 3306
    volumes:
      - ./res/db/mysql/db:/docker-entrypoint-initdb.d